# Generated by Django 3.0.2 on 2020-01-25 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigadores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, verbose_name='Fecha')),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='doi')),
                ('bibcode', models.CharField(blank=True, max_length=80, verbose_name='bibcode')),
                ('titulo', models.TextField(blank=True, max_length=15000, verbose_name='titulo')),
                ('autores', models.TextField(blank=True, max_length=15000, verbose_name='autores')),
                ('estudiantesEnArticulo', models.CharField(blank=True, max_length=150, verbose_name='Estudiantes en el articulo')),
                ('revistaPublicacion', models.CharField(blank=True, max_length=150)),
                ('paginas', models.CharField(blank=True, max_length=150)),
                ('volumen', models.CharField(blank=True, max_length=150)),
                ('url', models.CharField(blank=True, max_length=550)),
                ('anexoPdf', models.FileField(blank=True, upload_to='anexos/pdfs/', verbose_name='archivo PDF')),
                ('numeral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.Numeral')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'biblioteca',
                'verbose_name_plural': 'bibliotecas',
                'ordering': ['-fecha'],
            },
        ),
    ]
