# Generated by Django 3.0.2 on 2020-02-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20200131_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='autores',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='autores'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='bibcode',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='bibcode'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='doi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='doi'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='estudiantesEnArticulo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Estudiantes en el articulo'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='paginas',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='revistaPublicacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='titulo',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='url',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='volumen',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
