# Generated by Django 3.0.2 on 2020-02-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20200207_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='fecha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha'),
        ),
    ]
