# Generated by Django 3.0.3 on 2020-02-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_biblioteca_fecha_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='anexoPdf',
            field=models.FileField(blank=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
    ]
