# Generated by Django 3.0.3 on 2020-02-11 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_auto_20200210_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biblioteca',
            old_name='anexoPdf',
            new_name='anexos',
        ),
    ]
