# Generated by Django 3.0.2 on 2020-01-29 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEstudiante', models.CharField(blank=True, max_length=500, verbose_name='Nombre de estudiantes')),
                ('anexoPdf', models.FileField(null=True, upload_to='anexos/pdfs/', verbose_name='archivo PDF')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de creacion')),
                ('numeral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.Numeral')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.Periodo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'campo Modelo 16',
                'verbose_name_plural': 'Campos del Modelo 16',
                'ordering': ['fechaCreacion'],
            },
        ),
    ]
