# Generated by Django 3.0.2 on 2020-01-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0002_modelo16'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo16',
            name='anexoPdf',
            field=models.FileField(blank=True, null=True, upload_to='anexos/pdfs/', verbose_name='archivo PDF'),
        ),
    ]
