# Generated by Django 3.0.2 on 2020-02-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0003_auto_20200129_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='fechaFin',
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fechaInicio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha del inicio de periodo'),
        ),
    ]
