# Generated by Django 3.0.3 on 2020-02-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0004_auto_20200208_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='anexoPdf',
            field=models.FileField(null=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
        migrations.AlterField(
            model_name='modelo1',
            name='anexoPdf',
            field=models.FileField(null=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
        migrations.AlterField(
            model_name='modelo10',
            name='anexoPdf',
            field=models.FileField(null=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
        migrations.AlterField(
            model_name='modelo11',
            name='anexoPdf',
            field=models.FileField(null=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
        migrations.AlterField(
            model_name='modelo12',
            name='anexoPdf',
            field=models.FileField(null=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
        migrations.AlterField(
            model_name='modelo13',
            name='anexoPdf',
            field=models.FileField(null=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
        migrations.AlterField(
            model_name='modelo14',
            name='anexoPdf',
            field=models.FileField(null=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
        migrations.AlterField(
            model_name='modelo15',
            name='anexoPdf',
            field=models.FileField(null=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
        migrations.AlterField(
            model_name='modelo16',
            name='anexoPdf',
            field=models.FileField(blank=True, null=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
        migrations.AlterField(
            model_name='modelo2',
            name='anexoPdf',
            field=models.FileField(null=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
        migrations.AlterField(
            model_name='modelo3',
            name='anexoPdf',
            field=models.FileField(null=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
        migrations.AlterField(
            model_name='modelo4',
            name='anexoPdf',
            field=models.FileField(null=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
        migrations.AlterField(
            model_name='modelo5',
            name='anexoPdf',
            field=models.FileField(blank=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
        migrations.AlterField(
            model_name='modelo6',
            name='anexoPdf',
            field=models.FileField(null=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
        migrations.AlterField(
            model_name='modelo7',
            name='anexoPdf',
            field=models.FileField(null=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
        migrations.AlterField(
            model_name='modelo8',
            name='anexoPdf',
            field=models.FileField(null=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
        migrations.AlterField(
            model_name='modelo9',
            name='anexoPdf',
            field=models.FileField(null=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
    ]
