# Generated by Django 3.0.3 on 2020-02-11 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0005_auto_20200210_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citas',
            old_name='anexoPdf',
            new_name='anexos',
        ),
        migrations.RenameField(
            model_name='modelo1',
            old_name='anexoPdf',
            new_name='anexos',
        ),
        migrations.RenameField(
            model_name='modelo10',
            old_name='anexoPdf',
            new_name='anexos',
        ),
        migrations.RenameField(
            model_name='modelo11',
            old_name='anexoPdf',
            new_name='anexos',
        ),
        migrations.RenameField(
            model_name='modelo12',
            old_name='anexoPdf',
            new_name='anexos',
        ),
        migrations.RenameField(
            model_name='modelo13',
            old_name='anexoPdf',
            new_name='anexos',
        ),
        migrations.RenameField(
            model_name='modelo14',
            old_name='anexoPdf',
            new_name='anexos',
        ),
        migrations.RenameField(
            model_name='modelo15',
            old_name='anexoPdf',
            new_name='anexos',
        ),
        migrations.RenameField(
            model_name='modelo16',
            old_name='anexoPdf',
            new_name='anexos',
        ),
        migrations.RenameField(
            model_name='modelo2',
            old_name='anexoPdf',
            new_name='anexos',
        ),
        migrations.RenameField(
            model_name='modelo3',
            old_name='anexoPdf',
            new_name='anexos',
        ),
        migrations.RenameField(
            model_name='modelo4',
            old_name='anexoPdf',
            new_name='anexos',
        ),
        migrations.RenameField(
            model_name='modelo5',
            old_name='anexoPdf',
            new_name='anexos',
        ),
        migrations.RenameField(
            model_name='modelo6',
            old_name='anexoPdf',
            new_name='anexos',
        ),
        migrations.RenameField(
            model_name='modelo7',
            old_name='anexoPdf',
            new_name='anexos',
        ),
        migrations.RenameField(
            model_name='modelo8',
            old_name='anexoPdf',
            new_name='anexos',
        ),
        migrations.RenameField(
            model_name='modelo9',
            old_name='anexoPdf',
            new_name='anexos',
        ),
    ]
