# Generated by Django 3.0.3 on 2020-02-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0006_auto_20200210_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo1',
            name='fecha',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fecha del articulo'),
        ),
    ]
