# Generated by Django 3.0.3 on 2020-02-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0007_modelo1_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo14',
            name='participantes',
        ),
        migrations.AddField(
            model_name='modelo14',
            name='url',
            field=models.CharField(blank=True, max_length=100, verbose_name='url'),
        ),
    ]
