# Generated by Django 3.0.3 on 2020-03-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0010_auto_20200304_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo8',
            name='url',
        ),
        migrations.AddField(
            model_name='modelo8',
            name='financiamiento',
            field=models.CharField(blank=True, max_length=500, verbose_name='financiamiento'),
        ),
    ]
