# Generated by Django 3.0.3 on 2020-03-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0011_auto_20200304_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo9',
            name='doi',
            field=models.CharField(blank=True, max_length=500, verbose_name='doi'),
        ),
    ]
