# Generated by Django 3.0.3 on 2020-03-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0012_modelo9_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo1',
            name='autores',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='Nombre de los autores'),
        ),
        migrations.AlterField(
            model_name='modelo1',
            name='doi',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de doi'),
        ),
        migrations.AlterField(
            model_name='modelo1',
            name='estudiantesEnArticulo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre de los estudiantes en el articulo'),
        ),
        migrations.AlterField(
            model_name='modelo1',
            name='fecha',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fecha del articulo'),
        ),
        migrations.AlterField(
            model_name='modelo1',
            name='revistaPublicacion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre de la revista o publicacion'),
        ),
        migrations.AlterField(
            model_name='modelo1',
            name='titulo',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='Nombre del titulo'),
        ),
        migrations.AlterField(
            model_name='modelo1',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='url del articulo'),
        ),
        migrations.AlterField(
            model_name='modelo10',
            name='descripcion',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='modelo10',
            name='fecha',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='modelo10',
            name='periodoNumeral',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='periodo'),
        ),
        migrations.AlterField(
            model_name='modelo10',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='modelo11',
            name='descripcion',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='modelo11',
            name='fecha',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='modelo11',
            name='nombreEstudiante',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre del estudiante'),
        ),
        migrations.AlterField(
            model_name='modelo12',
            name='laboratorioTaller',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Laboratorio o taller'),
        ),
        migrations.AlterField(
            model_name='modelo13',
            name='agenciasFinancieras',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Agencias Financieras'),
        ),
        migrations.AlterField(
            model_name='modelo13',
            name='descripcion',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='modelo14',
            name='TelescopioInstrumentoInfra',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Opciones'),
        ),
        migrations.AlterField(
            model_name='modelo14',
            name='conferenciaProyecto',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Conferencia o proyecto'),
        ),
        migrations.AlterField(
            model_name='modelo14',
            name='descripcion',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='modelo14',
            name='fecha',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='modelo14',
            name='rol',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='modelo14',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='modelo15',
            name='descripcion',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='modelo16',
            name='anexos',
            field=models.FileField(null=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
        migrations.AlterField(
            model_name='modelo16',
            name='coordinacion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Coordinacion'),
        ),
        migrations.AlterField(
            model_name='modelo16',
            name='grado',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Grado'),
        ),
        migrations.AlterField(
            model_name='modelo16',
            name='nombreEstudiante',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre de estudiantes'),
        ),
        migrations.AlterField(
            model_name='modelo2',
            name='descripcion',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='modelo2',
            name='estudiantes',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='estudiantes'),
        ),
        migrations.AlterField(
            model_name='modelo2',
            name='nombreProyecto',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre del proyecto'),
        ),
        migrations.AlterField(
            model_name='modelo2',
            name='participantes',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='participantes'),
        ),
        migrations.AlterField(
            model_name='modelo2',
            name='responsableTecParticipante',
            field=models.CharField(blank=True, choices=[('Responsable', 'Responsable'), ('Técnico', 'Tecnico'), ('Participante', 'Participante')], max_length=500, null=True, verbose_name='responsable,tecnico o participante'),
        ),
        migrations.AlterField(
            model_name='modelo3',
            name='autores',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='Nombre de los autores'),
        ),
        migrations.AlterField(
            model_name='modelo3',
            name='doi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='DOI/ISBN'),
        ),
        migrations.AlterField(
            model_name='modelo3',
            name='estudiantes',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Nombre de los estudiantes'),
        ),
        migrations.AlterField(
            model_name='modelo3',
            name='fecha',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='modelo3',
            name='nombreConferencia',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre de la conferencia'),
        ),
        migrations.AlterField(
            model_name='modelo3',
            name='presentacionPoster',
            field=models.CharField(blank=True, choices=[('presentacion oral', 'presentacion oral'), ('poster', 'poster')], max_length=500, null=True, verbose_name='Presentacion oral o poster'),
        ),
        migrations.AlterField(
            model_name='modelo3',
            name='tituloPresentacion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Titulo de la presentacion'),
        ),
        migrations.AlterField(
            model_name='modelo3',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre de la url'),
        ),
        migrations.AlterField(
            model_name='modelo4',
            name='fecha',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='modelo4',
            name='nombreCompleto',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='modelo4',
            name='tituloTesis',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Titulo de tesis'),
        ),
        migrations.AlterField(
            model_name='modelo4',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='link de la url'),
        ),
        migrations.AlterField(
            model_name='modelo5',
            name='anexos',
            field=models.FileField(blank=True, null=True, upload_to='anexos/', verbose_name='archivo PDF'),
        ),
        migrations.AlterField(
            model_name='modelo5',
            name='nombreCurso',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre del Curso'),
        ),
        migrations.AlterField(
            model_name='modelo5',
            name='notas',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='modelo5',
            name='periodoNumeral',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Periodo del numeral'),
        ),
        migrations.AlterField(
            model_name='modelo6',
            name='Grado',
            field=models.CharField(blank=True, choices=[('licenciatura', 'licenciatura'), ('maestría', 'maestría'), ('doctorado', 'doctorado')], max_length=500, null=True, verbose_name='Tipo de grado'),
        ),
        migrations.AlterField(
            model_name='modelo6',
            name='fecha',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='modelo6',
            name='institucion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Institucion'),
        ),
        migrations.AlterField(
            model_name='modelo6',
            name='nombre',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='modelo6',
            name='notas',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='notas'),
        ),
        migrations.AlterField(
            model_name='modelo6',
            name='tituloTesis',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='titulo de la tesis'),
        ),
        migrations.AlterField(
            model_name='modelo7',
            name='autores',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='autores'),
        ),
        migrations.AlterField(
            model_name='modelo7',
            name='descripcion',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='modelo7',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='modelo8',
            name='descripcion',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='modelo8',
            name='financiamiento',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='financiamiento'),
        ),
        migrations.AlterField(
            model_name='modelo8',
            name='nombre',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='modelo8',
            name='participantes',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='participantes'),
        ),
        migrations.AlterField(
            model_name='modelo9',
            name='autores',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='autores'),
        ),
        migrations.AlterField(
            model_name='modelo9',
            name='doi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='doi'),
        ),
        migrations.AlterField(
            model_name='modelo9',
            name='fecha',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='modelo9',
            name='numeroReportes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='numero de reportes'),
        ),
        migrations.AlterField(
            model_name='modelo9',
            name='revistaPublicacion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='revista o publicacion'),
        ),
        migrations.AlterField(
            model_name='modelo9',
            name='titulo',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='modelo9',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='url'),
        ),
    ]
