# Generated by Django 3.0.5 on 2020-04-20 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteenviado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelo9',
            name='numeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.Numeral'),
        ),
        migrations.AddField(
            model_name='modelo9',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.Periodo'),
        ),
        migrations.AddField(
            model_name='modelo9',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelo8',
            name='numeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.Numeral'),
        ),
        migrations.AddField(
            model_name='modelo8',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.Periodo'),
        ),
        migrations.AddField(
            model_name='modelo8',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelo7',
            name='numeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.Numeral'),
        ),
        migrations.AddField(
            model_name='modelo7',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.Periodo'),
        ),
        migrations.AddField(
            model_name='modelo7',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelo6',
            name='numeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.Numeral'),
        ),
        migrations.AddField(
            model_name='modelo6',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.Periodo'),
        ),
        migrations.AddField(
            model_name='modelo6',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelo5',
            name='numeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.Numeral'),
        ),
        migrations.AddField(
            model_name='modelo5',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.Periodo'),
        ),
        migrations.AddField(
            model_name='modelo5',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelo4',
            name='numeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.Numeral'),
        ),
        migrations.AddField(
            model_name='modelo4',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.Periodo'),
        ),
        migrations.AddField(
            model_name='modelo4',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelo3',
            name='numeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.Numeral'),
        ),
        migrations.AddField(
            model_name='modelo3',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.Periodo'),
        ),
        migrations.AddField(
            model_name='modelo3',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelo2',
            name='numeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.Numeral'),
        ),
        migrations.AddField(
            model_name='modelo2',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.Periodo'),
        ),
        migrations.AddField(
            model_name='modelo2',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelo16',
            name='numeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.Numeral'),
        ),
        migrations.AddField(
            model_name='modelo16',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.Periodo'),
        ),
        migrations.AddField(
            model_name='modelo16',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelo15',
            name='numeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.Numeral'),
        ),
        migrations.AddField(
            model_name='modelo15',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.Periodo'),
        ),
        migrations.AddField(
            model_name='modelo15',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelo14',
            name='numeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.Numeral'),
        ),
        migrations.AddField(
            model_name='modelo14',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.Periodo'),
        ),
        migrations.AddField(
            model_name='modelo14',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelo13',
            name='numeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.Numeral'),
        ),
        migrations.AddField(
            model_name='modelo13',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.Periodo'),
        ),
        migrations.AddField(
            model_name='modelo13',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelo12',
            name='numeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.Numeral'),
        ),
        migrations.AddField(
            model_name='modelo12',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.Periodo'),
        ),
        migrations.AddField(
            model_name='modelo12',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelo11',
            name='numeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.Numeral'),
        ),
        migrations.AddField(
            model_name='modelo11',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.Periodo'),
        ),
        migrations.AddField(
            model_name='modelo11',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelo10',
            name='numeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.Numeral'),
        ),
        migrations.AddField(
            model_name='modelo10',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.Periodo'),
        ),
        migrations.AddField(
            model_name='modelo10',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelo1',
            name='numeral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.Numeral'),
        ),
        migrations.AddField(
            model_name='modelo1',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.Periodo'),
        ),
        migrations.AddField(
            model_name='modelo1',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citas',
            name='numeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.Numeral'),
        ),
        migrations.AddField(
            model_name='citas',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.Periodo'),
        ),
        migrations.AddField(
            model_name='citas',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
