# Generated by Django 3.0.5 on 2020-07-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citas',
            options={'ordering': ['usuario'], 'verbose_name': 'cita del periodo', 'verbose_name_plural': 'Citas del periodo'},
        ),
    ]
