# Generated by Django 3.0.5 on 2020-05-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_remove_citas_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='citas',
            field=models.IntegerField(default=0, verbose_name='Citas'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='citas_en_periodo',
            field=models.IntegerField(default=0, verbose_name='Citas durante periodo del reporte'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='indiceH',
            field=models.IntegerField(default=0, verbose_name='Indice H'),
        ),
    ]
