# Generated by Django 3.0.5 on 2020-05-27 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='numeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reportes.Numeral'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='usuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
